### ISSUE TITLE
Translate inserts, weak,very weak, strong ... 

### ISSUE THREAD

**Issue by ma-gu-16** [rollerworks/PasswordStrengthValidator#51]
Is it possible to translate? the text inserts?

e.g. uppercase letters, very weak, strong
i tried every lang.key but no success, i translated alreade the full sentences but not this inserts. 

thank you.

**Comment by sstok** [comment]
All the validators use the Symfony Translator, if you use the Symfony Framework this will use the application-wide translator.

If you use the validator stand-alone or in a custom set-up you can pass a custom translator to the constructor of `PasswordStrengthValidator`. Use the `ContainerConstraintValidatorFactory` and provide a service container that can resolve the `PasswordStrengthValidator` as a service by this full class-name `\Rollerworks\Component\PasswordStrength\Validator\Constraints\PasswordStrengthValidator::class`. Instead of the `ConstraintValidatorFactory`.

(For further assistance please use the Symfony provided support channels https://symfony.com/support )

To use a different translation you can add your own translations later than the once's provides with this library.
For the FrameworkBundle this means register your own bundle later than `PasswordStrengthBundle`, for a stand-alone this means you need to add another resource later (but again, please the support channels).

Hope this helps.
